spring.application.name=cep.lookup.api
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=1h

# desabilita banner desnecessário
spring.main.banner-mode=off

# loga as chamadas HTTP feitas pelo RestClient
logging.level.org.springframework.web.client=DEBUG
